name: jirafy-changelog-and-release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Jirafy Changelog
        id: changelog
        uses: ./
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          jiraHost: 'coltdorsey.atlassian.net'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: npm install --production

      # Sync the changelog with Jira projects / Tickets
      - name: Jirafy Sync
        uses: onXmaps/jirafy-sync@v2.0.1
        with:
          changelog: ${{ steps.changelog.outputs.changelog }}
          jiraVersion: ${{ github.ref_name }}
          jiraHost: ${{ secrets.JIRA_HOST }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraToken: ${{ secrets.JIRA_TOKEN }}
